### PR TITLE
Reset Value Curve buttons

### LINKED ISSUE #3759: Debug assertion failure: fpp_app_icon_svg is getting strlen'd but not null terminated
**Describe the bug**
Nondeterministic behavior on xLights startup, prevents startup in the debugger.
fpp_app_icon_svg is getting strlen'd but isn't null terminated.

**To Reproduce**
Start xlights under the debugger.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2023.04 / master

**Additional context**
This is probably a case of using the wrong constructor in BitmapCache.cpp, it could pass the length as well as the pointer so that there is no strlen call:

```
 wxBitmapBundle BitmapCache::GetFPPIcon() {
-    return wxBitmapBundle::FromSVG((const char*)fpp_app_icon_svg, wxSize(16, 16));
+    return wxBitmapBundle::FromSVG((const wxByte*)fpp_app_icon_svg, sizeof(fpp_app_icon_svg), wxSize(16, 16));
 }
```

### PR DESCRIPTION
**Pull request by merryoncherry**
A few cases where the value curve bitmap button wasn't reset when resetting the panel via SetDefaultParameters().  See issue #3775.
Also fixes #3759.
Verified that this doesn't cause any rendering differences in a small test set that tries to do a little bit of everything.

### CODE REVIEW

File: xLights/BitmapCache.cpp [hunk 1]
```diff
@@ -601,7 +601,7 @@ wxBitmapBundle BitmapCache::GetModelGroupIcon() {
     return CreateBitmapBundleFromXPMs(16, "ModelGroup", {model_16, model_64, model_64, model_64, model_64});
 }
 wxBitmapBundle BitmapCache::GetFPPIcon() {
```
Comment (merryoncherry) [inline xLights/BitmapCache.cpp:603]: The former call is for a string terminated with \0, but this fpp_app_icon_svg does not end in \0.  Drives the autodebugger nuts.
